"""
Created by Epic at 9/24/20
"""


class BaseContext:
    def __init__(self, client, data):
        """
        Basic context, used with client.get_context
        :param client: the client
        """
        self.client = client
        self.data = data

        # This possibly sucks performance wise? Please make a pr if there is a better way to do this.
        for field, field_data in data.items():
            setattr(self, field, field_data)


class MessageContext(BaseContext):
    """
    Message context

    Autogenerated by BaseContext
    """
    pass
